### ISSUE TITLE
issue with installing lans due to dependency python2-nfqueue

### ISSUE THREAD

**Issue by archey** [DanMcInerney/LANs.py#12]
We are trying to build the lans package and everything works fine except for issues with nfqueue. We have installed the nfqueue python2 package and installed _nfqueue.so and nfqueue.py under /usr/ib/python2.7/site-packages, but when we try to load nfqueue we get an error:

Traceback (most recent call last):
  File "/usr/bin/lans", line 36, in <module>
    import nfqueue
  File "/usr/lib/python2.7/site-packages/nfqueue.py", line 28, in <module>
    _nfqueue = swig_import_helper()
  File "/usr/lib/python2.7/site-packages/nfqueue.py", line 24, in swig_import_helper
    _mod = imp.load_module('_nfqueue', fp, pathname, description)
ImportError: dynamic module does not define init function (init_nfqueue)

Do you have any idea why we are getting this traceback

Nov 11 17:33 /usr/lib/python2.7/site-packages/nfqueue.py
Nov 11 17:33 /usr/lib/python2.7/site-packages/_nfqueue.so

**Comment by noraj1337** [comment]
It seems there are no more python-nfqueue AUR package.

**Comment by rpdelaney** [comment]
+1. I don't know how to get nfqueue in archlinux.
