### ISSUE TITLE
Aircrack-ng

### ISSUE THREAD

**Issue by t94j0** [DanMcInerney/LANs.py#39]
Hey, I can use aircrack-ng as a command, but when I try to run LANS, it gives me an error saying "Enabling monitor mode failed, do you have aircrack-ng installed?" The answer seems obvious. "Install aircrack-ng!" But, I already have it downloaded.

**Comment by m4rc3l** [comment]
same issue on kali linux 1.1.0 using AR9485 Wireless Network Adapter (rev 01), Enabling monitor mode failed, but manually checked and confirmed that monitor mode is active on wlan0 (AR9485) ...

**Comment by hamdi-charef** [comment]
Is this solution is solved?
I still get the same error.
Thanks

**Comment by DanMcInerney** [comment]
I don't maintain this script much nowadays cuz mitmf by byt3bl33d3r does
everything lanspy does plus more and is maintained but this should be an
easy fix, probably an output change from the cmd its using. I know some
better ways to get this info using netifaces lib instead so whenever I get
time I'll try to get to this.
