### ISSUE TITLE
KALI 2.0 Error

### ISSUE THREAD

**Issue by arsivcix** [DanMcInerney/LANs.py#59]
Hello.
Thank you for this program but I cannot see this is working.

After I set the Victims IP address I see this error.

`*] Hit Ctrl-C at any time to stop and choose a victim IP
^C
[*] Turning off monitor mode
[*] Enter the non-router IP to spoof: 192.168.1.3
[*] Checking the DHCP and DNS server addresses...
Traceback (most recent call last):
  File "LANs.py", line 1220, in <module>
    LANsMain(args)
  File "LANs.py", line 198, in LANsMain
    ans, unans = srp(dhcp, timeout=5, retry=1)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 357, in srp
    s = conf.L2socket(iface=iface, filter=filter, nofilter=nofilter, type=type)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 417, in __init__
    self.ins.bind((iface, type))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 19] No such device
`
I install the metasploit framework pro from rapid7 but its still doesnt work.

Is there any way to pass this error.

**Comment by tommp4** [comment]
@arsivcix did you find a solution?

**Comment by arsivcix** [comment]
No..
But i use mitmf instead of this.
İf its work LANs is more user friendly.
23 Nis 2016 17:21 tarihinde "tommp4" <notifications@github.com> yazdı:

**Comment by DanMcInerney** [comment]
Yeah I was going to suggest MITMF. LANs.py is basically a dead project to me because even if I fixed all the problems with it it still won't do all the stuff MITMF does so seems pointless to maintain this.
